
logging: False
#日志"
port: 17860
#webui 默认启动端口号"
llm_type: szz
#llm模型类型:glm6b、rwkv、llama、replitcode
llm_models: 
  szz: 
     path: "../Models/szz-0513.pth"
     #rwkv模型位置"
     strategy: "cuda fp16"
     #rwkv模型参数"
     historymode: string
     #rwkv历史记录实现方式：state、string
library: 
     strategy: "agents:0"
     #知识库参数，每组参数间用空格分隔，冒号前为知识库类型，后为抽取数量。

     #知识库类型:
     #bing        cn.bing搜索，仅国内可用，目前处于服务降级状态
     #sosowx      sogo微信公众号搜索，可配合相应auto实现全文内容分析
     #fess        fess搜索引擎
     #rtst        支持实时生成的sentence_transformers
     #remote      调用远程闻达知识库，用于集群化部署
     #kg          知识图谱,暂未启用
     #特殊库：
     #mix         根据参数进行多知识库融合
     #agents      提供网络资源代理，没有知识库查找功能，所以数量为0
     #            （目前stable-diffusion的auto脚本需要使用其中功能，同时需开启stable-diffusion的api功能）

     count: 1
     #最大抽取数量（所有知识库总和）

     show_soucre: true
     #知识库显示来源

     step: 0
     #知识库默认上下文步长
librarys: 
  bing: 
    count: 5
     #最大抽取数量